#pragma once

#define RGBLIGHT_DEFAULT_MODE 0 // static mode 0
#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 0
#define RGBLIGHT_DEFAULT_VAL 0

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 7

#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 120
#define TAPPING_TERM 200
#define FLOW_TAP_TERM 200

#define CHORDAL_HOLD
